name: Terraform CI/CD for S3 Static Site

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  terraform:
    name: Deploy static site
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform

    steps:
    - name: Checkout repository on our runner.
      uses: actions/checkout@v3
        
    - name: Setup Terraform with the same version as the project.
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify your preferred version
    
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
    - name: Terraform format
      id: fmt
      run: terraform fmt -check
    
    - name: Terraform validate
      id: validate
      run: terraform validate
      
    - name: Terraform plan
      id: plan
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform plan -no-color -input=false
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
